openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /governance/chainConfig:
    post:
      operationId: chainConfig
      summary: "governance_chainConfig"
      description: |
        The chainConfig property provides the latest chain configuration. This is equivalent to chainConfigAt() with an empty parameter.

        **NOTE:** In versions earlier than Klaytn v1.10.0, this API returned the initial chain configuration. However, due to its confusing name, it is updated since Klaytn v1.10.0. To query the initial chain configuration, use chainConfigAt(0) instead.

        **JSONRPC:** `governance_chainConfig`

      tags:
        - governance

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                  properties:
                    method:
                      type: string
                      default: 'governance_chainConfig'

      responses:
        200:
          description: Current chain configuration
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: object
                        description: Current chain configuration
                        example: {
                          chainId: 1001,
                          deriveShaImpl: 2,
                          governance: {
                            govParamContract: "0x0000000000000000000000000000000000000000",
                            governanceMode: "ballot",
                            governingNode: "0xe733cb4d279da696f30d470f8c04decb54fcb0d2",
                            kip71: {
                              basefeedenominator: 20,
                              gastarget: 30000000,
                              lowerboundbasefee: 25000000000,
                              maxblockgasusedforbasefee: 60000000,
                              upperboundbasefee: 750000000000
                            },
                            reward: {
                              deferredTxFee: true,
                              kip82ratio: "20/80",
                              minimumStake: 5000000,
                              mintingAmount: 6400000000000000000,
                              proposerUpdateInterval: 3600,
                              ratio: "50/40/10",
                              stakingUpdateInterval: 20,
                              useGiniCoeff: false
                            }
                          },
                          istanbul: {
                            epoch: 20,
                            policy: 2,
                            sub: 1
                          },
                          istanbulCompatibleBlock: 0,
                          koreCompatibleBlock: 0,
                          londonCompatibleBlock: 0,
                          magmaCompatibleBlock: 0,
                          unitPrice: 25000000000
                        }

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/governance/chainConfig.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/governance/GovernanceChainConfigExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/governance/chainConfig.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/governance/chainConfig.py"
