generatorName: web3rpc-javascript
outputDir: ./openapi/subbridge
inputSpec: ../../../rpc-specs/namespaces/subbridge-openapi.yaml
projectName: opensdk-javascript-subbridge
templateDir: ./template
sortParamsByRequiredFlag: false
globalProperties:
  apiDocs: false
  modelDocs: false
  modelTests: false
  apiTests: true
inlineSchemaNameMappings:
  accountCreated_default_response: AccountCreatedResponse
  getRewards_default_response: GetRewardsResponse
  ethAccounts_default_response: EthAccountsDefaultResponse
  ethBlockNumber_default_response: EthBlockNumberDefaultResponse
  ethCall_default_response: EthCallDefaultResponse